### ISSUE TITLE
400 Bad Request when trying to create a custom log alert monitor

### ISSUE THREAD

**Issue by PaulBanusIAD** [DataDog/serverless-plugin-datadog#440] opened 2023-11-02 14:52 UTC
## Expected Behavior

Creation of a custom log alert monitor

## Actual Behavior

I have the error `Error occurred when configuring monitors: 400 Bad Request: This could be due to incorrect syntax for apigateway_warning`

## Steps to Reproduce the Problem

  1. Create the monitor with the serverless framework with the following configuration

```
- apigateway_warning:
          name: "APIgateway 4XX"
          type: "log alert"
          query: "logs(\"source:apigateway status:warn @http.status_code:4* @API-Gateway.env:prod\").index(\"*\").rollup(\"count\").last(\"1h\") > 100"
          message: "toto"
          priority: 2
          options:
            thresholds:
              ok: 0
              critical: 100
```

When using the Datadog API via curl to create the monitor, I have no error and the monitor is created
```
curl -X POST "https://api.datadoghq.eu/api/v1/monitor"  -H "Accept: application/json" -H "Content-Type: application/json" -H "DD-API-KEY: SECRET" -H "DD-APPLICATION-KEY: SECRET" -d '{ "name": "APIgateway 4XX", "priority": 2, "message": "toto",   "type": "log alert",  "options": {"thresholds": {  "ok": 0,  "critical": 100}  },  "query": "logs(\"source:apigateway status:warn @http.status_code:4* @API-Gateway.env:prod\").index(\"*\").rollup(\"count\").last(\"1h\") > 100"}'
```

The validate route for the Datadog API returns no error 
```
curl -X POST "https://api.datadoghq.eu/api/v1/monitor/validate"  -H "Accept: application/json" -H "Content-Type: application/json" -H "DD-API-KEY: SECRET" -H "DD-APPLICATION-KEY: SECRET" -d '{ "name": "APIgateway 4XX", "priority": 2, "message": "toto",   "type": "log alert",  "options": {"thresholds": {  "ok": 0,  "critical": 100}  },  "query": "logs(\"source:apigateway status:warn @http.status_code:4*  @API-Gateway.env:prod\").index(\"*\").rollup(\"count\").last(\"1h\") > 100"}'
```

## Specifications

  - Serverless Framework version: ~3.24.1
  - Datadog Serverless Plugin version: 5.16.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): nodejs16.x
   
## Stacktrace
  
No stacktrace except the error message `Error occurred when configuring monitors: 400 Bad Request: This could be due to incorrect syntax for apigateway_warning`

**Comment by Morpheusse** [comment] 2024-01-09 11:37
I am having a simular issue, have you been able to resolved yours?

**Comment by scottmurray14** [comment] 2024-01-10 15:49
Having same issue. Any fix @PaulBanusIAD?

**Comment by freyam13** [comment] 2024-01-22 21:45
Same issue here as well.

**Comment by duncanista** [comment] 2024-03-13 12:28
Hey – sorry everyone for the inconvenience. I'm going to be working on this. It seems the problem is deeper than I expected. I'll keep you posted and will link a pull request eventually.

**Comment by duncanista** [comment] 2024-03-13 13:11
Hello @PaulBanusIAD,

Sorry for taking a long time to answer.
I tried reproducing this with the following configuration:
```yaml
    monitors:
      - apigateway_warning:
          name: "APIgateway 4XX"
          type: "log alert"
          tags: ["team:serverless", "service:hello-world"].     # required by my org
          query: "logs(\"source:apigateway status:warn @http.status_code:4* @API-Gateway.env:prod\").index(\"*\").rollup(\"count\").last(\"1h\") > 100"
          message: "toto"
          priority: 2
          options: 
            include_tags: true                                  # required by my org
            thresholds:
              ok: 0
              critical: 100
```

Same configuration as provided. I'm using the version `5.59.0`. Yet, I was successful on the creation of the monitor.
I might think you might be missing required tags from your organization? Please let me know if the issue still persist. I was not able to reproduce the problem.

Here's a screenshot of the monitor in Datadog.
<img width="1477" alt="Screenshot 2024-03-13 at 9 11 06 AM" src="https://github.com/DataDog/serverless-plugin-datadog/assets/30836115/1142f707-d8d3-48b0-a109-1e0652663660">

**Comment by duncanista** [comment] 2024-03-20 17:01
Hey everyone – I'm going to go ahead and close this since I had no apparent issue with reproduction and there hasn't been a reply to the thread! Feel free to re-open if needed.

**Closed by duncanista** 2024-03-20 17:01 UTC
Labels: bug
