### ISSUE TITLE
Node 18 with a aws-sdk V2 Import

### ISSUE THREAD

**Issue by Mattensor** [DataDog/serverless-plugin-datadog#331] opened 2023-01-03 07:32 UTC
## Expected/Actual Behavior

I'm running a lambda on Node 18, when I invoke my lambda I get the following error `"Error: Cannot find module 'aws-sdk/clients/dynamodb'`. I understand that Lambdas with a Node 18 runtime have the SDK v3 available, by the looks of it the SDK datadog stack trace requires v2. With a runtime of Node 16, I have no issue at all with the DD plugin.

Here are the layers ->

<img width="1618" alt="image" src="https://user-images.githubusercontent.com/10224902/210315328-1920333d-4976-404a-865c-5ecbb22f2853.png">

Appreciate your help, thank you 🙏

## Steps to Reproduce the Problem

  1. Deploy a node 18 lambda with serverless-plugin-datadog
  2. Invoke the lambda

## Specifications

  - Serverless Framework version: 3.25.1
  - Datadog Serverless Plugin version: 5.15.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): Node 18
  
## Stacktrace
  
```
2023-01-03T07:07:25.106Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'aws-sdk/clients/dynamodb'\nRequire stack:\n- /var/task/src/functions/api/handler.js\n- /opt/nodejs/node_modules/datadog-lambda-js/runtime/user-function.js\n- /opt/nodejs/node_modules/datadog-lambda-js/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'aws-sdk/clients/dynamodb'",
        "Require stack:",
        "- /var/task/src/functions/api/handler.js",
        "- /opt/nodejs/node_modules/datadog-lambda-js/runtime/user-function.js",
        "- /opt/nodejs/node_modules/datadog-lambda-js/runtime/index.js",
        "    at ImportModuleError.ExtendedError [as constructor] (/opt/nodejs/node_modules/datadog-lambda-js/runtime/errors.js:113:28)",
        "    at new ImportModuleError (/opt/nodejs/node_modules/datadog-lambda-js/runtime/errors.js:123:42)",
        "    at /opt/nodejs/node_modules/datadog-lambda-js/runtime/user-function.js:273:31",
        "    at step (/opt/nodejs/node_modules/datadog-lambda-js/runtime/user-function.js:43:23)",
        "    at Object.throw (/opt/nodejs/node_modules/datadog-lambda-js/runtime/user-function.js:24:53)",
        "    at rejected (/opt/nodejs/node_modules/datadog-lambda-js/runtime/user-function.js:16:65)"
    ]
}
```

**Comment by astuyve** [comment] 2023-01-25 21:09
Hi, I've tested and tried to reproduce this (albeit using the aws-sdk v3 and kinesis), but have been unable to.

`dd-trace-js` doesn't support `aws-sdk-v3` yet, but it doesn't fail. With our new coldstart tracing feature I can confirm the library is loaded:
<img width="650" alt="image" src="https://user-images.githubusercontent.com/1598537/214690712-0fea795e-d4ac-45e8-bbe5-6f035ca08ac1.png">

Because dd-trace doesn't fully support it yet, the result is only an HTTP request here:
<img width="560" alt="image" src="https://user-images.githubusercontent.com/1598537/214690858-c53d942a-be1a-4505-9012-5f4502c8a504.png">


At a glance, that import looks a little off? I think there's a hyphen for the clients:
```js
// ES5 example
const { DynamoDBClient, BatchExecuteStatementCommand } = require("@aws-sdk/client-dynamodb");
// ES6+ example
import { DynamoDBClient, BatchExecuteStatementCommand } from "@aws-sdk/client-dynamodb";
```
That's based on the [docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb/index.html)


Can you try this snippet instead and report back? Thanks!

**Comment by astuyve** [comment] 2023-02-07 16:45
Closing this as there's been no update for a few weeks. Please let me know if change the import declaration fixes this issue for you.

Thanks!

**Closed by astuyve** 2023-02-07 16:45 UTC
