### ISSUE TITLE
ES2015 default imports are incorrectly patched

### ISSUE THREAD

**Issue by jimmyn** [DataDog/serverless-plugin-datadog#10] opened 2019-11-11 08:30 UTC
After enabling this plugin I get `Cannot set property 'default' of undefined"` error in all functions that use `handler.default` reference in `serverles.yml`

## Steps to Reproduce the Problem

  1. Create a simple sls function with `handler: myFunc/handler.default`
  2. Add `serverless-plugin-datadog`
 

## Specifications

  - Serverless Framework version:   1.57.0
  - Datadog Serverless Plugin version: 0.7.0
  - Lambda function runtime: Node 10.x
  
## Stacktrace
  
  ```
{
  errorType: "TypeError",
  errorMessage: "Cannot set property 'default' of undefined",
  stack: [
    "TypeError: Cannot set property 'default' of undefined",
    "    at Module.<anonymous> (/var/task/datadog_handlers/webpack:/datadog_handlers/updateAppStatisticsHook.js:3:1)",
    "    at Module.<anonymous> (/var/task/datadog_handlers/updateAppStatisticsHook.js:96722:30)",
    "    at __webpack_require__ (/var/task/datadog_handlers/webpack:/webpack/bootstrap:19:1)",
    "    at /var/task/datadog_handlers/webpack:/webpack/bootstrap:83:1",
    "    at Object.<anonymous> (/var/task/datadog_handlers/updateAppStatisticsHook.js:87:10)",
    "    at Module._compile (internal/modules/cjs/loader.js:778:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)",
    "    at Module.load (internal/modules/cjs/loader.js:653:32)",
    "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)",
    "    at Module.require (internal/modules/cjs/loader.js:692:17)",
    "    at require (internal/modules/cjs/helpers.js:25:18)",
    "    at _tryRequire (/var/runtime/UserFunction.js:75:12)",
    "    at _loadUserApp (/var/runtime/UserFunction.js:95:12)",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
    "    at Object.<anonymous> (/var/runtime/index.js:45:30)"
  ]
}
  ```

**Comment by DarcyRaynerDD** [comment] 2019-11-11 15:00
Hey @jimmyn, thanks for opening this issue. This looks like an edge case we overlooked when we built the plugin, so it should be an easy fix. In the meantime if this is blocking you, you can follow the manual instrumentation instructions [here](https://github.com/DataDog/datadog-lambda-layer-js)

**Comment by DarcyRaynerDD** [comment] 2019-11-11 18:22
Hmm, so I haven't had any luck reproducing this. Are you using web packing to transform your es6 modules? Do you think you be able to send a minimal example repo that reproduces the issue?

**Comment by agocs** [comment] 2020-02-13 21:16
Hey, I'm going to close this issue for the time being. @jimmyn , please feel free to re-open or open a new issue if you're able to create a minimal reproduction

**Closed by agocs** 2020-02-13 21:16 UTC
