### ISSUE TITLE
Warmup plugin can't init datadog No API key configure

### ISSUE THREAD

**Issue by ycrc5** [DataDog/serverless-plugin-datadog#421] opened 2023-08-31 15:37 UTC
## Expected Behavior
Warmup lambda functions are able to startup and execute

## Actual Behavior
Warmup lambda functions crash with errors relating to `No API key configure`

## Steps to Reproduce the Problem

  1. Setup a serverless 3 project with datadog and warmup plugin using the packages and plugin sections below.
  1. Deploy and compare logs of warmup plugin and a service setup lambda. Notice that the functions for the services are working as expected and that only the functions created by the warmup plugin are resulting in the error.
  1. Double check that the ENV values are the same for both lambdas

## Specifications

1. Serverless framework related packages:

``` json
{
   "serverless": "3.20.0",
    "serverless-export-env": "^2.2.0",
    "serverless-offline": "^12.0.4",
    "serverless-plugin-datadog": "^5.38.1",
    "serverless-plugin-warmup": "8.1.0",
    "serverless-prune-plugin": "^2.0.2",
    "serverless-s3-cleaner": "^2.0.2",
    "serverless-webpack": "^5.3.1",
}
```

2. Plugins section:

```yaml
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-plugin-warmup
  - serverless-plugin-datadog
  - serverless-export-env
  - serverless-s3-cleaner
```

3. Custom config for plugins
``` yaml
  warmup:
    default:
      enabled: true

  datadog:
    addExtension: true
    apiKeySecretArn: ... redacted ...
    enableSourceCodeIntegration: true
    service: ... redacted ...
    version: ${file(./package.json):version}
    tags: '... redacted ...'
    env: ${self:custom.stage}
```

  - Lambda function runtime (Python 3.7, Node 10, etc.): Node 16
  
## Stacktrace
  
  ```
  INIT_START Runtime Version: nodejs:16.v18	Runtime Version ARN: ... redacted ...
2023-08-31 14:17:36 UTC | DD_EXTENSION | ERROR | No API key configured
TELEMETRY	Name: datadog-agent	State: Subscribed	Types: [Platform, Function, Extension]
2023-08-31 14:17:36 UTC | DD_EXTENSION | ERROR | Unable to load trace agent config: you must specify an API Key, either via a configuration file or the DD_API_KEY env var
2023-08-31 14:17:36 UTC | DD_EXTENSION | ERROR | Unexpected nil instance of the trace-agent
EXTENSION	Name: datadog-agent	State: Registered	Events: [INVOKE, SHUTDOWN]

  ```

**Comment by sfirrin** [comment] 2023-09-06 17:55
Hi @ycrc5 I just set up a new project with the Datadog plugin and serverless-plugin-warmup and I am not able to reproduce the issue (removed request ID from logs):

```
TELEMETRY	Name: datadog-agent	State: Subscribed	Types: [Platform, Function, Extension]
--
EXTENSION	Name: datadog-agent	State: Ready	Events: [INVOKE, SHUTDOWN]
START Version: $LATEST
2023-09-06T17:46:47.458Z	INFO	Warm Up Start
2023-09-06T17:46:47.519Z	INFO	Warming up function: node-warmup-plugin-test-dev-function1 with concurrency: 10
2023-09-06T17:46:52.419Z	INFO	Warm Up Invoke Success: node-warmup-plugin-test-dev-function1
2023-09-06T17:46:52.419Z	INFO	Warm Up Finished with 0 invoke errors
END RequestId:
```

I see you are using serverless-webpack as well and suspect that might be playing a role. Could you open a support case at https://www.datadoghq.com/support/ so we can get all the details of your situation and help further?

**Comment by ycrc5** [comment] 2023-09-07 11:08
Hi @sfirrin . Thanks for having a look. Ill reach out to the support page with more info. That said, our engineers have managed to resolve the issue for the warmup plugin by setting the following values:

```yaml
warmup:
    default:
      enabled: true
      environment:
        DD_API_KEY: ... redacted ...
```

This now adds both the api key and secret arn:
<img width="274" alt="Screenshot 2023-09-07 at 13 06 21" src="https://github.com/DataDog/serverless-plugin-datadog/assets/121860892/bf2f42ba-4e98-4219-aaa0-26ae08015a03">

Its weird that the other functions in the service are working without an issue. Seems like the code regarding the secret arn is not working as expected?

**Comment by sfirrin** [comment] 2023-09-07 14:58
That's interesting, thank you for sharing the workaround. I suspect with webpack maybe there is something going wrong with the interaction between the two plugins. Not sure what the difference would be between my example and yours but in mine the DD_API_KEY variable is set on the warmup plugin without setting the environment variable on the warmup plugin config. Thanks again for opening this, I'm going to close this out and we can follow up through support.

**Closed by sfirrin** 2023-09-07 14:58 UTC
