### ISSUE TITLE
Unable to detect compiler type when installing with yarn 

### ISSUE THREAD

**Issue by k2tomasz** [DataDog/serverless-plugin-datadog#422] opened 2023-08-31 16:35 UTC
At least please confirm this is safe to ignore for now.

## Expected Behavior
No Errors 

## Actual Behavior

Error message when running yarn install.

## Steps

1. Add serverless-plugin-datadog to package.json
2. Run yarn install

## Specifications

  - Serverless Framework version: 3.34.0
  - Datadog Serverless Plugin version: 5.42.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): runtime: nodejs18.x
  
## Stacktrace
[4/4] Building fresh packages...
[-/17] ⠠ waiting...
[13/17] ⠠ cpu-features
[-/17] ⠠ waiting...
[-/17] ⠠ waiting...
  warning Error running install script for optional dependency: "node_modules\\cpu-features: Command failed.
Exit code: 1
Command: node buildcheck.js > buildcheck.gypi && node-gyp rebuild
Arguments:
Directory: node_modules\\cpu-features
Output: node_modules\\buildcheck\\lib\\index.js:133
        throw new Error('Unable to detect compiler type');
        ^

Error: Unable to detect compiler type
    at new BuildEnvironment (\node_modules\\buildcheck\\lib\\index.js:133:15)
    at Object.<anonymous> (node_modules\\cpu-features\\buildcheck.js:5:12)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)

success Saved lockfile.
Done in 163.37s.

**Comment by sfirrin** [comment] 2023-09-05 14:43
Hi @k2tomasz thanks for opening this

I'm not able to reproduce on Mac Monterey, could you give more detail about your node version / OS / when you encounter this problem?

Searching I found a similar issue https://github.com/DataDog/datadog-ci/issues/714 in datadog-ci which is a dependency of this library, but this was apparently fixed in https://github.com/DataDog/datadog-ci/pull/943 2.16.1 while we use a newer version https://github.com/DataDog/serverless-plugin-datadog/blob/master/package.json#L59

**Comment by k2tomasz** [comment] 2023-09-06 12:06
Tested on WSL (Ubuntu) and it does not work either.

**Comment by naomichi-y** [comment] 2023-09-09 15:28
I am having the same problem and the error occurs when I run yarn install in a Docker container environment.
Using serverless-plugin-datadog 5.44.0 and have confirmed that datadog/datadog-ci `^2.17.2` is used in yarn.lock.

* Serverless Framework version: 3.34.0
* Datadog Serverless Plugin version: 5.42.0
* Lambda function runtime (Python 3.7, Node 10, etc.): runtime: nodejs16.x
* Host OS: Amazon Linux 2 (Intel)

```
# package.json
{
  "dependencies": {
    "serverless-plugin-datadog": "^5.44.0",
    "yarn": "^1.22.19"
  }
}
```

```
# Dockerfile
FROM amazon/aws-lambda-ruby:3.2

WORKDIR /app

# https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-up-node-on-ec2-instance.html
# Amazon Linux 2 does not currently support the current LTS release (version 18.x) of Node.js. Use Node.js version 16.x with the following command instead.
RUN curl -sL https://rpm.nodesource.com/setup_17.x | bash -
RUN yum install -y nodejs ca-certificates && \
  rm -rf /var/cache/yum/* && \
  yum clean all
RUN npm install -g yarn

COPY package.json yarn.lock ./
RUN yarn global add serverless@3.34.0
RUN yarn
```

```
# docker build .
Step 9/11 : RUN yarn
 ---> Running in 8fc93e58b9c4
yarn install v1.22.19
warning package.json: No license field
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > serverless-plugin-datadog@5.44.0" has unmet peer dependency "serverless@3.x || 2.x || 1.x".
[4/4] Building fresh packages...
warning Error running install script for optional dependency: "/app/node_modules/cpu-features: Command failed.
Exit code: 1
Command: node buildcheck.js > buildcheck.gypi && node-gyp rebuild
Arguments:
Directory: /app/node_modules/cpu-features
Output:
/app/node_modules/buildcheck/lib/index.js:115
  throw new Error('Unable to detect compiler type');
  ^

Error: Unable to detect compiler type
    at BuildEnvironment.getKind (/app/node_modules/buildcheck/lib/index.js:115:9)
    at BuildEnvironment.tryCompile (/app/node_modules/buildcheck/lib/index.js:537:15)
    at BuildEnvironment.checkHeader (/app/node_modules/buildcheck/lib/index.js:423:25)
    at Object.<anonymous> (/app/node_modules/cpu-features/buildcheck.js:16:4)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

Node.js v17.9.0"
info This module is OPTIONAL, you can safely ignore this error
success Saved lockfile.
Done in 18.02s.
Removing intermediate container 8fc93e58b9c4
 ---> c5b1a2c8b3e1
```

However, the subsequent RUN seems to be executed, although an error is generated.

**Comment by sfirrin** [comment] 2023-09-12 17:31
Interesting, thanks for sharing @naomichi-y. We still need to track down the cause of this

@k2tomasz does this prevent you from installing / building, or just show the error message? If it is the error message only, from what I can tell this should be safe to ignore

**Comment by k2tomasz** [comment] 2023-09-15 11:59
@sfirrin everything seems to be working fine. just not sure why i see that error..

**Comment by naomichi-y** [comment] 2023-09-15 12:19
https://github.com/DataDog/serverless-plugin-datadog/issues/422#issuecomment-1712537305
I had this problem in an Amazon Linux 2 environment and was able to eliminate the problem by installing the following package.

```
yum install -y make gcc gcc-c++ make python3
```

```
[4/4] Building fresh packages...
success Installed "serverless@3.34.0" with binaries:
      - serverless
      - sls
Done in 19.25s.
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.83s.
```

There was no problem before, but I don't know why the error occurred.

**Comment by astuyve** [comment] 2023-11-22 01:33
Closing this as the last two comments indicate other changes solve the issue. Please feel free to re-open this or a support ticket if there are any concerns.

Thanks!

**Closed by astuyve** 2023-11-22 01:33 UTC
