### ISSUE TITLE
Unable to build / test / contribute

### ISSUE THREAD

**Issue by adambartholomew** [DataDog/serverless-plugin-datadog#34] opened 2020-03-24 12:50 UTC
## Expected Behavior
I was going to make a PR contribution to this project, but I was unable to build and test the changes.

Failure are related to not being able to generate a `layers.json` file. Not having this file blocks both the build and the test runner.

## Actual Behavior
User should be able to contribute following posted guidelines in markdown readme.

## Steps to Reproduce the Problem

1. Fork and clone the repo
2. Install yarn dependencies
3. Attempt to run the build - informed you must run `generate_layers_json.sh`
4. Run `./scripts/generate_layers_json.sh`
5. Unable to poll layers

![image](https://user-images.githubusercontent.com/324503/77427106-2de4e700-6dac-11ea-8588-5d218f28770e.png)

## Specifications

  - Serverless Framework version: N/A
  - Datadog Serverless Plugin version: `master`
  - Lambda function runtime (Python 3.7, Node 10, etc.): node 12
  
## Stacktrace
  
N/A

**Comment by DarcyRaynerDD** [comment] 2020-03-24 15:07
Hi @adambartholomew,
Thanks for your interest in contributing. I think the problem is, at the moment the ./scripts/generate_layers_json looks for layers based on the account of your current AWS credentials, which doesn't work for anyone outside of Datadog. We can probably solve this by just checking in that JSON file.

**Comment by DarcyRaynerDD** [comment] 2020-03-25 19:29
@adambartholomew  Okay, I've checked in the layers.json master. Let us know if that fixes the issue for you

**Closed by DarcyRaynerDD** 2020-03-25 19:29 UTC
