### ISSUE TITLE
subscribeToApiGatewayLogs: false causes 502 and no logs on dashboard

### ISSUE THREAD

**Issue by ebsaral** [DataDog/serverless-plugin-datadog#147] opened 2021-07-15 11:03 UTC
## Expected Behavior

We want to see the function logs on both serverless and datadog, and have a successful execution. 

## Actual Behavior

Currently our endpoints are giving 502 internal error.

## Steps to Reproduce the Problem

  1. Remove log groups of development environment from AWS
  2. Call the endpoints again so log groups get populated
  3. Deploy to development environment with these settings in serverless.yml:

```
dd_enabled:
    local: false
    development: true
    production: false
datadog:
    enabled: ${self:custom.dd_enabled.${sls:stage}, false}
    site: datadoghq.eu
    forwarder: arn:aws:lambda:eu-central-XXXXXXXXXX
    subscribeToApiGatewayLogs: false
```
  4. Deployment is successful but we are not seeing any log on Serverless dashboard anymore and we cannot execute the functions due to an internal error in datadog-lambda-js as the last end which is a dependency I guess.
  5. When I remove `subscribeToApiGatewayLogs: false`, it works.

## Specifications

  - Serverless Framework version: 
    - Framework Core: 2.51.0
      Plugin: 5.4.3
      SDK: 4.2.3
      Components: 3.13.3
  - Datadog Serverless Plugin version: 2.27.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): Node 14
  
## Stacktrace
  
  ```
{
                "trace_id": "68028eb3864a1576",
                "span_id": "68028eb3864a1576",
                "parent_id": "0000000000000000",
                "name": "aws.lambda",
                "resource": "checkout-api-development-process_create_deal",
                "error": 1,
                "meta": {
                    "_dd.origin": "lambda",
                    "service": "checkout-api-development-process_create_deal",
                    "cold_start": "true",
                    "function_arn": "arn:aws:lambda:eu-central-1:747800237849:XXXXXXXXXXXXXX",
                    "function_version": "$LATEST",
                    "request_id": "ef0f17fa-7b42-4fbd-a31b-140975742c9a",
                    "resource_names": "checkout-api-development-process_create_deal",
                    "datadog_lambda": "3.56.0",
                    "dd_trace": "0.34.0",
                    "function_trigger.event_source": "api-gateway",
                    "function_trigger.event_source_arn": "arn:aws:apigateway:eu-central-1::/restapis/7p608b3ccf/stages/development",
                    "http.url": "dev-api-checkout.finn.auto",
                    "http.url_details.path": "/processDealCreation",
                    "http.method": "POST",
                    "http.status_code": "502",
                    "error.type": "TypeError",
                    "error.msg": "Cannot read property 'then' of null",
                    "error.stack": "TypeError: Cannot read property 'then' of null\n    at /opt/nodejs/node_modules/datadog-lambda-js/utils/handler.js:152:57\n    at Object.<anonymous> (/opt/nodejs/node_modules/datadog-lambda-js/index.js:168:62)\n    at step (/opt/nodejs/node_modules/datadog-lambda-js/index.js:44:23)\n    at Object.next (/opt/nodejs/node_modules/datadog-lambda-js/index.js:25:53)\n    at /opt/nodejs/node_modules/datadog-lambda-js/index.js:19:71\n    at new Promise (<anonymous>)\n    at __awaiter (/opt/nodejs/node_modules/datadog-lambda-js/index.js:15:12)\n    at /opt/nodejs/node_modules/datadog-lambda-js/index.js:162:108\n    at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:96:56\n    at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:47:56\n    at Scope._activate (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/scope/async_resource.js:53:14)\n    at Scope.activate (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:12:19)\n    at DatadogTracer.trace (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:47:35)\n    at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:96:23\n    at Object.<anonymous> (/opt/nodejs/node_modules/datadog-lambda-js/index.js:187:31)\n    at step (/opt/nodejs/node_modules/datadog-lambda-js/index.js:44:23)\n    at Object.next (/opt/nodejs/node_modules/datadog-lambda-js/index.js:25:53)\n    at fulfilled (/opt/nodejs/node_modules/datadog-lambda-js/index.js:16:58)"
                },
                "metrics": {
                    "_dd.agent_psr": 1,
                    "_sample_rate": 1,
                    "_sampling_priority_v1": 1
                },
                "start": 1626345838760067300,
                "duration": 81641113,
                "service": "aws.lambda",
                "type": "serverless"
            }
  ```

**Comment by tianchu** [comment] 2021-08-04 03:45
@ebsaral I tried both the latest version of the plugin and the 3.27.0, used a node.14x function and `subscribeToApiGatewayLogs` set to `false`. I could not reproduce the issue. Are you able to supply a small (e.g., hello-world like) sample application for us to reproduce?

Was there any error messages when you run `sls deploy`?

**Comment by ebsaral** [comment] 2021-08-09 07:54
> @ebsaral I tried both the latest version of the plugin and the 3.27.0, used a node.14x function and `subscribeToApiGatewayLogs` set to `false`. I could not reproduce the issue. Are you able to supply a small (e.g., hello-world like) sample application for us to reproduce?
> 
> Was there any error messages when you run `sls deploy`?

Thanks for checking it out @tianchu 

I think the issue doesn't occur when a fresh deployment is made. 

Have you tried these steps in order to reproduce the issue?
1. Deploy to sls without subscribeToApiGatewayLogs option.
2. Remove log groups of  from AWS
3. Deploy to sls with subscribeToApiGatewayLogs option.

If you have done this already, I can try to create a replica repo for the issue. 

Thank you!

**Comment by tianchu** [comment] 2021-08-09 15:00
@ebsaral I have not (will try), and I assume by "log groups" you meant the Lambda log groups (not the API Gateway log groups)?

**Comment by ebsaral** [comment] 2021-08-09 15:51
@tianchu I believe they are API Gateway logs. Here is a screenshot where I removed them:

<img width="400" alt="Screenshot 2021-08-09 at 17 49 47" src="https://user-images.githubusercontent.com/2864828/128735431-b47851aa-9f4b-44b2-b985-2f5b56509300.png">

**Comment by tianchu** [comment] 2021-08-09 16:25
@jcstorms1 can you follow up here given that you are really familiar with the `subscribeToApiGatewayLogs` option? 

@ebsaral wonder if you mind joining https://github.com/DataDog/serverless-plugin-datadog#community and reach out to @jcstorms1 for quick feedback loop? Hopefully we can identify the root cause really quickly with your help. Thank you for reporting the issue!

**Comment by jcstorms1** [comment] 2021-08-13 18:06
@ebsaral I'm also having difficulties replicating this error following the steps you provided. At this point, it would be helpful to get a sample app that contains your serverless configs if you don't mind. 

I'd also be interested to know if you have Execution Logging set up for these gateways, or if only Access Logging is enabled. Note that if you set up your gateways with Serverless and include `provider.logs.restApi:true`, it will enable both Access and Execution logging by default. If you are manually setting up logging for your gateways, both will need to be enabled separately. 

The reason I ask is because there is another[ issue open](https://github.com/DataDog/serverless-plugin-datadog/issues/142) where log groups were deleted, and when we tried to recreate the Execution Log Group it led to an error because it was not deleted with the stack. I'm investigating that as well and it would be interesting if these are the same issue manifested differently. Thanks!

**Comment by astuyve** [comment] 2021-10-17 15:45
Closing this issue as it's been 2 months with no reply. Please re-open if necessary!

**Closed by astuyve** 2021-10-17 15:45 UTC
Labels: bug
