### ISSUE TITLE
Console Patching Doesn't Consider stdout and stderr

### ISSUE THREAD

**Issue by shellscape** [DataDog/serverless-plugin-datadog#74] opened 2020-10-15 14:10 UTC
## Expected Behavior

I'd expect all data sent to logs to contain the trace id prefix, including output contained in `stdout` and `stderr`, as `console.*` writes to these streams. 

## Actual Behavior

Anything written directly with `stdout` or `stderr` lacks the trace id prefix. Only logs written with `console.*` are prefixed.

No doubt there were considerations made in choosing to only patch `console.*` methods, but for the ecosystem, the decision is rather short-sighted. At this point in time, our only choice is to create a writable stream that wraps `console.*` - that comes with massive performance implications as output in `pino` is compiled for what `stdout.write`/`sterr.write` expect, and requires a large amount of extra processing to prepare a single log message for use in `console.*` (mostly due to line break issues). We've seen an order of magnitude increase in the amount of time a log line takes to be sent to the std stream as a result.

I might be having an "it's too early in the day moment," but I'm unable to track down where the monkeypatching of `console.log` is taking place within this package, so handling that ourselves isn't looking too promising. 

## Steps to Reproduce the Problem

  1. Add [`pino`](https://github.com/pinojs/pino) to any serverless project utilizing this plugin
  1. Initialize a new logger with default settings
  1. Log data
  1. Observe the lack of prefix in datadog

## Specifications

  - Serverless Framework version: 1.78.1
  - Datadog Serverless Plugin version: ^2.5.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): Node 12
  
## Stacktrace
  
  ```
n/a
  ```

**Comment by DarcyRaynerDD** [comment] 2020-10-15 14:34
Hi @shellscape.

So, the trace log correlation is handled in a combination of datadog-lambda-js and dd-trace-js, which this plugin adds to your function via a Lambda Layer. dd-trace-js actually has an integration with pino that should add trace-id/span-id to your output. Something might be going wrong, so I'm going to see if I can reproduce this. If you could send us an example code snippet with your pino set up, that might help narrow down the issue as well.

**Comment by shellscape** [comment] 2020-10-15 14:44
> If you could send us an example code snippet with your pino set up, that might help narrow down the issue as well.

```js
const logger = pino(
  {
    level: 'info',
  }
);
```

That ought to do it. 

FWIW I've been source diving `dd-trace` and stumbled upon the `datadog-plugin-pino` package, but searching for that plugin (https://www.google.com/search?q=%22datadog-plugin-pino%22&oq=%22data&aqs=chrome.0.69i59l2j69i57j0i67i457j0i131i433j0i20i131i263i433j69i65l2.1226j0j1&sourceid=chrome&ie=UTF-8) yields all of 4 results, none of which are helpful. Searching for `"serverless-plugin-datadog" "pino"` yields no results. And the DataDog documentation doesn't appear to have anything related to `pino` when using the serverless plugin + layer.

**Comment by shellscape** [comment] 2020-10-15 14:51
There is also this comment from @rochdev which indicates there may be a problem initializing `pino` and `dd-trace` together: https://github.com/DataDog/dd-trace-js/issues/1025#issuecomment-662990505

**Comment by tianchu** [comment] 2021-08-04 19:16
@shellscape Sorry for the super late reply! But I just tested the latest version of the plugin with `pino` and iI had no issues. See my sample application: https://github.com/DataDog/datadog-lambda-js/issues/171#issuecomment-892719250. BTW, the automatic trace id injection only works when logging in JSON as pointed in our doc https://docs.datadoghq.com/tracing/connect_logs_and_traces/nodejs.

Not exactly sure what broke in your situation, but you can always inject trace id on your own too https://docs.datadoghq.com/tracing/connect_logs_and_traces/nodejs#manual-injection.

I'm going to close the issue for now, since I don't think we have identified any generally applicable issue here. But feel free to reopen if you still need help. You can also find us at https://chat.datadoghq.com/ (#serverless channel) for further discussion or contact Datadog Support for a deeper investigation on your issue.

**Closed by tianchu** 2021-08-04 19:16 UTC
Labels: dd-to-triage

**Comment by shellscape** [comment] 2021-08-04 19:23
Holy crap dude, that was almost a year ago.  Haven't used Datadog since Nov 2020 so there isn't even a means for me to counter. Y'all should consider setting up stalebot. Open source sponsored and owned by a company should have better response times. Whew.
