### ISSUE TITLE
plugin does not function with serverless dashboard

### ISSUE THREAD

**Issue by rparsonsbb** [DataDog/serverless-plugin-datadog#16] opened 2019-12-18 18:14 UTC
## Expected Behavior
`serverless-plugin-datadog` functions correctly and applies the datadog layer, but serverless dashboard pieces also work.

## Actual Behavior
```
[ERROR] AttributeError: module 'app' has no attribute 'handler'
Traceback (most recent call last):
  File "/var/task/serverless_sdk/__init__.py", line 107, in wrapped_handler
    return user_handler(event, context)
  File "/var/task/s_app.py", line 19, in error_handler
    raise e
  File "/var/task/s_app.py", line 14, in <module>
    user_handler = serverless_sdk.get_user_handler('datadog_handlers/app.handler')
  File "/var/task/serverless_sdk/__init__.py", line 57, in get_user_handler
    return getattr(user_module, user_handler_name)
```

If you comment out `app` and `org` in `serverless.yml` then the error does not occur and the app functions properly. 

## Steps to Reproduce the Problem

  1. clone https://github.com/rparsonsbb/flask-dd-serverless-plugin-example
  1. set `app`, `org` and `custom.datadog.apiKey`
  1. `sls deploy`
  1. attempt to call <url>/quote

## Specifications

  - Serverless Framework version: 
```
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              10.16.3
     Framework Version:         1.59.3
     Plugin Version:            3.2.6
     SDK Version:               2.2.1
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
```
  - Datadog Serverless Plugin version: 0.10.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): Python 3.7
  
## Stacktrace
  
  ```
[ERROR] AttributeError: module 'app' has no attribute 'handler'
Traceback (most recent call last):
  File "/var/task/serverless_sdk/__init__.py", line 107, in wrapped_handler
    return user_handler(event, context)
  File "/var/task/s_app.py", line 19, in error_handler
    raise e
  File "/var/task/s_app.py", line 14, in <module>
    user_handler = serverless_sdk.get_user_handler('datadog_handlers/app.handler')
  File "/var/task/serverless_sdk/__init__.py", line 57, in get_user_handler
    return getattr(user_module, user_handler_name)
  ```

**Comment by DarcyRaynerDD** [comment] 2020-01-29 16:08
Hi @rparsonsbb 👋 , sorry for the late reply and thanks for the detailed report. I can confirm I was able to reproduce this. It's important to note that both the serverless dashboard and our lambda integration work by adding a log group subscription to your lambdas. AWS has a limit of one subscription per log group, which might make these approaches ultimately incompatible. However what we can do is try and fix the error the function is throwing.

**Comment by hydrosquall** [comment] 2020-04-01 00:18
Hi @DarcyRaynerDD ,

I just ran into this same issue with a similar Flasky/WSGI handler application, but the error report from @rparsonsbb matched my experience exactly. 

Would it be feasible to use Datadog for some things (metrics, traces) and Serverless for others (logs) to overcome the single log group subscription issue? Separately, I don't know if the plugin has access to the serverless.yml file, but if so perhaps we could warn the user at deploy time that the two monitoring tools cannot be used together.

**Comment by anil-grexit** [comment] 2020-04-15 16:25
@hydrosquall I think you can make it work by not collecting logs through Datadog if you don't need. You can specify this in the `serverless.yml` like below:

```
custom:
  datadog:
    flushMetricsToLogs: true
```

On the other hand, for anyone looking to not send logs to Serverless Dashboard:
```
custom:
  enterprise:
    collectLambdaLogs: false
```

**Comment by agocs** [comment] 2021-08-04 15:10
Hey folks, I'm going to close this because:
- AWS now allows two subscriptions per log group
- serverless-plugin-datadog now defaults to installing the [Datadog Lambda Extension](https://github.com/datadog/datadog-lambda-extension) in Node and Python (>=3.7) runtimes

**Closed by agocs** 2021-08-04 15:10 UTC
Labels: dd-to-triage
