### ISSUE TITLE
Cloudwatch log group subscription filter being deleted/recreated alternately on every deployment

### ISSUE THREAD

**Issue by nmguse-bighealth** [DataDog/serverless-plugin-datadog#72] opened 2020-09-23 22:19 UTC
Running a serverless deploy causes the subscription filter to be alternately created and destroyed. One deployment will destroy the subscription filter and the next will create the subscription filter and repeat.

Config:
```
plugins:
  - serverless-plugin-datadog

custom:
  datadog:
    flushMetricsToLogs: true
    forwarder: <forwarder lambda arn>
```

## Expected Behavior
Subscription filter is created, not deleted

## Actual Behavior
Deploy 1:
CloudFormation - CREATE_COMPLETE - AWS::Logs::SubscriptionFilter - ServiceUnderscoremethodUnderscorecallLogGroupSubscription
CloudFormation - CREATE_COMPLETE - AWS::Logs::SubscriptionFilter - PostUnderscoredeployLogGroupSubscription

Deploy 2:
CloudFormation - DELETE_COMPLETE - AWS::Logs::SubscriptionFilter - ServiceUnderscoremethodUnderscorecallLogGroupSubscription
CloudFormation - DELETE_COMPLETE - AWS::Logs::SubscriptionFilter - PostUnderscoredeployLogGroupSubscription

Repeat

## Steps to Reproduce the Problem

  1. Serverless Deploy (subscribes first time)
  1. Serverless Deploy (unsubscribes)
  1. Serverless Deploy (subscribes)
  1. Serverless Deploy (unsubscribes)
  1. etc

## Specifications

  - Serverless Framework version: 1.70.0
  - Datadog Serverless Plugin version: 1.1.0
  - Lambda function runtime: Python 3.6

**Comment by Czechh** [comment] 2020-09-23 22:22
@nmguse-bighealth Thanks for the issue, I'm curious if this is something specific to that version, can you update to the latest version of the plugin and retry please?

**Comment by nmguse-bighealth** [comment] 2020-09-24 18:59
That seems to have fixed it; looks like this was already known and fixed, but it didn't come up in my searches:
https://github.com/DataDog/serverless-plugin-datadog/issues/66

**Comment by bryantbiggs** [comment] 2020-11-10 22:09
we are still seeing this on v2.5.0 and its getting quite frustrating - we will have to manually set these and add the manual script to our deploy pipeline just to ensure they stay on the log groups and not get removed because we rely on these for alerting and monitoring

<img width="978" alt="image" src="https://user-images.githubusercontent.com/10913471/98739508-7cfd7d80-2377-11eb-900e-0796eab7c7bf.png">

**Comment by Czechh** [comment] 2020-11-10 22:29
@bryantbiggs thanks for letting us know. Can I get a bit more details on how to reproduce this so we can address? Thank you.

I tried with a simple `serverless.yml` and couldn't repro.

**Comment by pyaesone17** [comment] 2020-12-05 15:02
I am also having this issue subscription randomly deleted and created

**Comment by pyaesone17** [comment] 2021-01-08 10:02
@Czechh Hi did u find any root cause for this issue ?

**Comment by Czechh** [comment] 2021-01-08 16:05
@pyaesone17 I haven't been able to reproduce this. Do you happen to have some steps to follow?

**Comment by bryantbiggs** [comment] 2021-01-08 17:02
@Czechh I'm afraid its not easy to repro - its sporadic whenever we do deploys and to recreate all of that would be quite difficult. What I can share is that we were using https://github.com/dougmoscrop/serverless-plugin-log-subscription before the datadog plugin started providing capabilities to subscribe the forwarder natively and we never experienced this issue with that plugin. we have contemplated turning off the datadog subscription and going back to that plugin, but for now we are running a script at the end of our pipelines to ensure the forwarder is subscribed correctly which only causes conflicts with the datadog plugin but hey, we don't lose our subscriptions

**Comment by pyaesone17** [comment] 2021-01-15 07:01
We used nested cloud formation stack though,  it might be related ?

**Comment by nhinsch** [comment] 2021-01-27 22:05
@bryantbiggs @pyaesone17 

While we have as of yet been unable to reproduce this issue or identify a root cause, we have recently released version 2.13.1 of the plugin with support for two subscription filters per CloudWatch log group. We recommend updating the plugin to the latest version, and please let us know if this issue continues to occur.

**Comment by bryantbiggs** [comment] 2021-01-27 22:06
thanks @nhinsch , will do

**Comment by zARODz11z** [comment] 2021-02-18 17:20
@bryantbiggs @pyaesone17 @nmguse-bighealth 
As Nick said above we recommend updating the plugin to the latest version, we have not been able to reproduce the issue on the latest versions of the plugin. I'm closing this issue for now, please reach out if the issue continues to occur.

**Closed by zARODz11z** 2021-02-18 17:20 UTC
