### ISSUE TITLE
express.request and pg.query APM missing after node 16 upgrade.

### ISSUE THREAD

**Issue by SuvabBaral** [DataDog/serverless-plugin-datadog#324] opened 2022-12-09 09:49 UTC
While using node version 10/12 with the following packages:
"serverless-plugin-datadog": "^2.34.1",
"pg": "^7.4.0", (node-postgres)
"express": "~4.15.5",
"datadog-lambda-js": "^6.85.0",

I was able to track the API calls and Database Queries using datadog.

But After upgrading to Node 16 the API calls, express.request APM and Database Queries APM are not viewable in datadog.

The environment variables such as DD_API_KEY, DD_ENV are all properly set.

## Expected Behavior
Able to view API(express.request) and Database(pg.query) related APM 
![outlook](https://user-images.githubusercontent.com/41819363/206664999-3c3467e5-18e7-4cf6-8afc-39c50f16d79f.png)

When I go inside the APM, I can see all the API calls that were made and from this I can use the trace for the metrics.

![apitraces](https://user-images.githubusercontent.com/41819363/206665021-4b8fb8bd-6b2a-4a68-a3df-b370f9d2ea58.png)

## Actual Behavior
As you can see the postgres APM is missing.
![currentoutlook](https://user-images.githubusercontent.com/41819363/206665352-e36b866d-c1d0-4fa1-9bcb-7242427faa7c.png)

And when I open the APM, there is no informative data about the API calls available.

![noapitraces](https://user-images.githubusercontent.com/41819363/206665725-16c72408-ca24-46ce-bf97-8ad8d52d718c.png)
And there are no details for API/express.request.

## Specifications

  - Serverless Framework version: 3.23.0
  - Datadog Serverless Plugin version: 5.13.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): Node 16
  - Datadog Lambda Js: 6.85.0
  - node-postgres (pg): 8.0.3
  - express: 4.15.5
These packages were updated to support node 16 runtime.

The datadog settings and the plugin is also added:

![Screenshot from 2022-12-09 15-25-58](https://user-images.githubusercontent.com/41819363/206673232-e42be0ae-639f-421d-bc4d-99ed34392bed.png)

![Screenshot from 2022-12-09 15-26-06](https://user-images.githubusercontent.com/41819363/206672522-e2a7a7c4-1b17-48f9-a134-421ab68b1250.png)

And the datadog layers also exist:
![datadog layers](https://user-images.githubusercontent.com/41819363/206691900-c410f76e-09cb-48e9-9a4a-950b450b214f.png)

**Comment by sfirrin** [comment] 2022-12-12 22:41
Hi @SuvabBaral, thanks for opening this issue  

Sorry I can't do it for you, but could you please open a ticket with this info at https://www.datadoghq.com/support/? Opening the ticket will allow us to see the traces sent and get all the information needed to figure out where the issue is.

**Comment by sulfanofikri** [comment] 2022-12-15 08:28
Hi,

i'm facing the same problem after upgrading NodeJS to 18 and serverless-plugin-datadog to 5
there is no `Trace` on Datadog Log

working well with Node 12

**Comment by kimi-p** [comment] 2022-12-16 15:02
👋  Hi @SuvabBaral and @sulfanofikri ,
We've tried this different app provided by other unrelated issue (https://github.com/DataDog/serverless-plugin-datadog/issues/321) which uses node16, express, and datadog-lambda-js layer v84, and that app in specific works as expected. Could you provide a reproducible app (removing all sensitive parts) so that we can investigate further?

BTW, the two `dns.lookup` traces can be disabled with `DD_TRACE_DISABLED_PLUGINS: dns` env var if it bothers you and is not the reason why the `aws.lambda` span did not show up.

**Comment by SuvabBaral** [comment] 2022-12-27 04:10
Hi @kimi-p and @sfirrin, 
Sorry for the late response. 

I have actually raised a support ticket with Datadog support and provided all the necessary details, including details of the app. I was informed that the issue is escalated to the engineering team and I am waiting for further response.

Also, thanks @kimi-p  for the suggestions and I want to inform that my Datadog Lambda layer looks like the following:
** Extension - arn:aws:lambda:us-east-1:xxxx:layer:Datadog-Extension:35
** Node16 Layer ARN - arn:aws:lambda:us-east-1:xxxx:layer:Datadog-Node16-x:85

I also see that @astuyve has mentioned that this issue is fixed in https://github.com/DataDog/dd-trace-js/pull/2625.
Is it fixed and any specific versions of package I should use for this?

**Comment by astuyve** [comment] 2023-01-25 21:17
Hi @SuvabBaral - this is fixed now with Node layer 86. In addition, I upstreamed this fix into `serverless-http` in this [pr](https://github.com/dougmoscrop/serverless-http/pull/263) (v3.1.1).

Please let me know if this doesn't resolve your case.

Thanks!

**Closed by astuyve** 2023-01-25 21:17 UTC
