### ISSUE TITLE
Slow lambda startup 

### ISSUE THREAD

**Issue by andremonteiro95** [DataDog/serverless-plugin-datadog#249] opened 2022-04-06 12:00 UTC
Since I added this package to my infrastructure, my lambdas take 5 to 6 seconds more to initialize (cold starts). Is there any way to reduce the start-up time?

**Comment by astuyve** [comment] 2022-04-06 13:08
hi @andremonteiro95 - thanks for reaching out! To help, I'll need more information.
Which runtime are you using?
Which version of the datadog layer and datadog extension are you using?
Can you compare the cold start performance between your instrumented application and non instrumented application? If so, what is the difference?

Datadog reports all of these metrics into the `Function` view. As an example, here you can see several functions (of various runtimes, memory configuration, and package size) report the cold starts over time:
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/1598537/161981786-a80ca52b-82fd-4f72-9ea8-40ad8d04098e.png">

**Comment by astuyve** [comment] 2022-04-06 14:38
Okay thanks @andremonteiro95 - that's far outside of the bounds we've observed (even during load tests).

`addLayers: false` will disable APM traces and metrics, which isn't something we'd want to suggest.

We'll need you to enable debug logs (`logLevel: debug`) and open a ticket with support so you can securely send the log data. From there, we can help troubleshoot the coldstart issue.

Thanks!

**Comment by astuyve** [comment] 2022-05-12 14:26
Hi @SethO - thanks for reaching out! Sorry for the delay, I've been on vacation while moving across the country.

While we are working behind the scenes in the datadog tracer(s) to improve tracing performance, there are several factors that go into cold start performance including specific DD configuration, Lambda configuration, and the Lambda Function code itself.

The best way I can help would be to ask you to open up a ticket with Datadog support and ask them to escalate it to me (they'll know 😉). We'll need to see which libraries you're using in your function(s) and try to understand their interaction with the [node tracer](https://github.com/DataDog/dd-trace-js), as well as understand the Lambda configuration you've chosen.

Thanks!

**Comment by inyutin** [comment] 2022-11-17 21:37
Unfortunately, this is still a problem with python environment and serverless plugin v5.10.0
Configuration:
```yaml
custom:
  datadog:
    site: datadoghq.eu
    apiKeySecretArn: arn:aws:secretsmanager:eu-west-2:077068547884:secret:DATADOG_API_KEY-ai9u6k
    tags: "stage:internal-test"
    enableDDTracing: false
    enableSourceCodeIntegration: false
```
![image](https://user-images.githubusercontent.com/28871177/202564774-f562ed88-4952-43c0-9090-e4b4ede8ecba.png)

**Comment by astuyve** [comment] 2022-11-17 21:45
Hi @inyutin, thanks for reaching out!

That graph looks like runtime duration? It's unclear to me if that's the actual reported initDuration (cold start time).

Either way, please open a support ticket and supply your `requirements.txt` along with other dependencies, and debug logs.

Given that this specific plugin library only instruments functions, and isn't used in the runtime, I'm going to close this issue.
For specific questions regarding runtimes, please open a support ticket or reach out on our open source slack for help.
Otherwise, if you've got a specific bug or reproducible example, please open a github issue in the respective runtime libraries (https://github.com/DataDog/datadog-lambda-js/, https://github.com/DataDog/datadog-lambda-python, etc)

Thank you!

**Closed by astuyve** 2022-11-17 21:45 UTC

**Comment by ezweave** [comment] 2022-11-21 22:39
@astuyve we're seeing the exact problem that @SethO [describes](https://github.com/DataDog/serverless-plugin-datadog/issues/249#issuecomment-1116158539).  We've mitigated it somewhat by fiddling with `provisionedConcurrency`, but we have similar graphs that show when we turn everything on:

```ts
datadog: {
      enableXrayTracing: true,
      captureLambdaPayload: true,
      addLayers: true,
}
```

Our cold start times increase drastically.  Is the only way to prevent this to turn these things off?  Was there any progress on this issue?  We're trying to improve performance in an API and these cold starts happen frequently enough to affect our `P90` numbers.

**Comment by astuyve** [comment] 2022-11-22 01:18
Hi @ezweave, thanks for reaching out!

Can you open a support ticket and share your plugin/library information, runtime, runtime dependencies, coldstart metrics, and other configuration? Distributed tracing for dynamic languages requires patching libraries, which happens at load time. Depending on which libraries you're using and how they are loaded, we likely can offer more specific advice for your situation.

We continue to work across runtimes to improve performance of active tracing, including a recent ~200ms [cold start improvement](https://github.com/DataDog/datadog-lambda-js/pull/302)
